### ISSUE TITLE
Criar um banco de dados e conectá-lo a API

### ISSUE THREAD

**Issue by guibrbs** [guibrbs/Orcatinhos#2]
Criar um banco de dados no MongoDB Atlas e conectar na aplicação com Node e Mongoose.

[Vídeo](https://www.youtube.com/watch?v=K5QaTfE5ylk&t=1058s&ab_channel=MatheusBattisti-HoradeCodar) que pode ser útil.

**Comment by julio-dourado** [comment]
Conclui essa issue na branch develop
